[2023-10-19T18:32:58.052+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [queued]>
[2023-10-19T18:32:58.060+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [queued]>
[2023-10-19T18:32:58.060+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-19T18:32:58.075+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-19 18:07:18.633128+00:00
[2023-10-19T18:32:58.083+0000] {standard_task_runner.py:57} INFO - Started process 51 to run task
[2023-10-19T18:32:58.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-19T18:07:18.633128+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmpjhwzdtid']
[2023-10-19T18:32:58.093+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask pokelist
[2023-10-19T18:32:58.159+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [running]> on host f04a086795a0
[2023-10-19T18:32:58.252+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T18:07:18.633128+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-19T18:07:18.633128+00:00'
[2023-10-19T18:32:58.257+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-19T18:32:58.258+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/pokelist.py']
[2023-10-19T18:32:58.282+0000] {subprocess.py:86} INFO - Output:
[2023-10-19T18:32:58.398+0000] {subprocess.py:93} INFO - python3: can't open file '/home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/pokelist.py': [Errno 2] No such file or directory
[2023-10-19T18:32:58.402+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-19T18:32:58.420+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-19T18:32:58.425+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple, task_id=pokelist, execution_date=20231019T180718, start_date=20231019T183258, end_date=20231019T183258
[2023-10-19T18:32:58.438+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 35 for task pokelist (Bash command failed. The command returned a non-zero exit code 2.; 51)
[2023-10-19T18:32:58.459+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T18:32:58.485+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
