[2023-10-19T18:07:20.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [queued]>
[2023-10-19T18:07:20.475+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [queued]>
[2023-10-19T18:07:20.476+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-19T18:07:20.491+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-19 18:07:18.633128+00:00
[2023-10-19T18:07:20.498+0000] {standard_task_runner.py:57} INFO - Started process 6017 to run task
[2023-10-19T18:07:20.509+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-19T18:07:18.633128+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmpm46lxlf8']
[2023-10-19T18:07:20.515+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask pokelist
[2023-10-19T18:07:20.584+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-19T18:07:18.633128+00:00 [running]> on host 3a678a96e860
[2023-10-19T18:07:20.667+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T18:07:18.633128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-19T18:07:18.633128+00:00'
[2023-10-19T18:07:20.670+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-19T18:07:20.670+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/pokelist.py']
[2023-10-19T18:07:20.691+0000] {subprocess.py:86} INFO - Output:
[2023-10-19T18:07:20.808+0000] {subprocess.py:93} INFO - python3: can't open file '/home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/pokelist.py': [Errno 2] No such file or directory
[2023-10-19T18:07:20.812+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-19T18:07:20.825+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-19T18:07:20.830+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231019T180718, start_date=20231019T180720, end_date=20231019T180720
[2023-10-19T18:07:20.844+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task pokelist (Bash command failed. The command returned a non-zero exit code 2.; 6017)
[2023-10-19T18:07:20.877+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T18:07:20.907+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
