[2023-10-19T15:06:17.536+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T15:06:16.107451+00:00 [queued]>
[2023-10-19T15:06:17.544+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-19T15:06:16.107451+00:00 [queued]>
[2023-10-19T15:06:17.544+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-19T15:06:17.558+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-19 15:06:16.107451+00:00
[2023-10-19T15:06:17.566+0000] {standard_task_runner.py:57} INFO - Started process 3208 to run task
[2023-10-19T15:06:17.570+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-19T15:06:16.107451+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmpo74_b3pt']
[2023-10-19T15:06:17.573+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask pokelist
[2023-10-19T15:06:17.648+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-19T15:06:16.107451+00:00 [running]> on host 3a678a96e860
[2023-10-19T15:06:17.727+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-19T15:06:16.107451+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-19T15:06:16.107451+00:00'
[2023-10-19T15:06:17.731+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-19T15:06:17.732+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/Airflow-docker/dags/pokelist.py']
[2023-10-19T15:06:17.749+0000] {subprocess.py:86} INFO - Output:
[2023-10-19T15:06:17.871+0000] {subprocess.py:93} INFO - python: can't open file '/home/debian/brincando-com-apis-publicas/git_data_engineer_kaique/Airflow-docker/dags/pokelist.py': [Errno 2] No such file or directory
[2023-10-19T15:06:17.875+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-10-19T15:06:17.902+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-10-19T15:06:17.910+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231019T150616, start_date=20231019T150617, end_date=20231019T150617
[2023-10-19T15:06:17.922+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task pokelist (Bash command failed. The command returned a non-zero exit code 2.; 3208)
[2023-10-19T15:06:17.943+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-19T15:06:17.968+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
