[2023-10-20T14:53:27.706+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.498512+00:00 [queued]>
[2023-10-20T14:53:27.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.498512+00:00 [queued]>
[2023-10-20T14:53:27.715+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-10-20T14:53:27.736+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-20 14:47:06.498512+00:00
[2023-10-20T14:53:27.745+0000] {standard_task_runner.py:57} INFO - Started process 5312 to run task
[2023-10-20T14:53:27.761+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-20T14:47:06.498512+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmp1msnnxlb']
[2023-10-20T14:53:27.774+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask pokelist
[2023-10-20T14:53:27.871+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-20T14:47:06.498512+00:00 [running]> on host 4662b0d5ca37
[2023-10-20T14:53:28.041+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:47:06.498512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:47:06.498512+00:00'
[2023-10-20T14:53:28.044+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-20T14:53:28.045+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/pokelist.py']
[2023-10-20T14:53:28.072+0000] {subprocess.py:86} INFO - Output:
[2023-10-20T14:53:29.624+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-10-20T14:53:34.236+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-10-20T14:53:34.236+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-10-20T14:53:34.592+0000] {subprocess.py:93} INFO - 23/10/20 14:53:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-10-20T14:53:36.757+0000] {subprocess.py:93} INFO - 23/10/20 14:53:36 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-10-20T14:57:38.099+0000] {subprocess.py:93} INFO - [Stage 0:>                                                          (0 + 0) / 4][Stage 0:>                                                          (0 + 1) / 4][Stage 0:>                                                          (0 + 4) / 4]ERROR:root:Exception while sending command.
[2023-10-20T14:57:38.101+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:38.101+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 516, in send_command
[2023-10-20T14:57:38.101+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError("Answer from Java side is empty")
[2023-10-20T14:57:38.101+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2023-10-20T14:57:38.101+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1038, in send_command
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO -     response = connection.send_command(command)
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/clientserver.py", line 539, in send_command
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO -     raise Py4JNetworkError(
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2023-10-20T14:57:38.102+0000] {subprocess.py:93} INFO - A Requisição de nº 1 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 2 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 3 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 4 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 5 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 6 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 7 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 8 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 9 coletou 50 Pokemons
[2023-10-20T14:57:38.103+0000] {subprocess.py:93} INFO - A Requisição de nº 10 coletou 50 Pokemons
[2023-10-20T14:57:38.104+0000] {subprocess.py:93} INFO - A Requisição de nº 11 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 12 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 13 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 14 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 15 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 16 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 17 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 18 coletou 50 Pokemons
[2023-10-20T14:57:38.106+0000] {subprocess.py:93} INFO - A Requisição de nº 19 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 20 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 21 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 22 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 23 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 24 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 25 coletou 50 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - A Requisição de nº 26 coletou 42 Pokemons
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/pokelist.py", line 41, in <module>
[2023-10-20T14:57:38.107+0000] {subprocess.py:93} INFO -     df_pokes = ss.read.json(df_pokes)
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/sql/readwriter.py", line 440, in json
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.json(jrdd))
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/java_gateway.py", line 1322, in __call__
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/pyspark/errors/exceptions/captured.py", line 179, in deco
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/py4j/protocol.py", line 334, in get_return_value
[2023-10-20T14:57:38.108+0000] {subprocess.py:93} INFO -     raise Py4JError(
[2023-10-20T14:57:38.109+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JError: An error occurred while calling o27.json
[2023-10-20T14:57:38.653+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-20T14:57:38.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-20T14:57:38.795+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=simple, task_id=pokelist, execution_date=20231020T144706, start_date=20231020T145327, end_date=20231020T145738
[2023-10-20T14:57:38.977+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task pokelist (Bash command failed. The command returned a non-zero exit code 1.; 5312)
[2023-10-20T14:57:39.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T14:57:39.462+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
