[2023-10-20T14:54:17.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.134310+00:00 [queued]>
[2023-10-20T14:54:17.540+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.134310+00:00 [queued]>
[2023-10-20T14:54:17.541+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-10-20T14:54:17.582+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): pokelist> on 2023-10-20 14:46:35.134310+00:00
[2023-10-20T14:54:17.602+0000] {standard_task_runner.py:57} INFO - Started process 6185 to run task
[2023-10-20T14:54:17.609+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simple', 'pokelist', 'manual__2023-10-20T14:46:35.134310+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/pokelist.py', '--cfg-path', '/tmp/tmp10y3geal']
[2023-10-20T14:54:17.621+0000] {standard_task_runner.py:85} INFO - Job 87: Subtask pokelist
[2023-10-20T14:54:17.748+0000] {task_command.py:416} INFO - Running <TaskInstance: simple.pokelist manual__2023-10-20T14:46:35.134310+00:00 [running]> on host 4662b0d5ca37
[2023-10-20T14:54:17.977+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@***.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simple' AIRFLOW_CTX_TASK_ID='pokelist' AIRFLOW_CTX_EXECUTION_DATE='2023-10-20T14:46:35.134310+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-20T14:46:35.134310+00:00'
[2023-10-20T14:54:17.990+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-20T14:54:17.991+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python3 /opt/***/scripts/pokelist.py']
[2023-10-20T14:54:18.040+0000] {subprocess.py:86} INFO - Output:
[2023-10-20T14:54:23.013+0000] {subprocess.py:93} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2023-10-20T14:54:57.940+0000] {subprocess.py:93} INFO - Setting default log level to "WARN".
[2023-10-20T14:54:57.941+0000] {subprocess.py:93} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2023-10-20T14:55:01.077+0000] {subprocess.py:93} INFO - 23/10/20 14:55:01 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2023-10-20T14:55:31.759+0000] {subprocess.py:93} INFO - 23/10/20 14:55:31 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2023-10-20T14:55:31.777+0000] {subprocess.py:93} INFO - 23/10/20 14:55:31 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2023-10-20T14:57:37.614+0000] {subprocess.py:93} INFO - A Requisição de nº 1 coletou 50 Pokemons
[2023-10-20T14:57:37.624+0000] {subprocess.py:93} INFO - A Requisição de nº 2 coletou 50 Pokemons
[2023-10-20T14:57:37.624+0000] {subprocess.py:93} INFO - A Requisição de nº 3 coletou 50 Pokemons
[2023-10-20T14:57:37.624+0000] {subprocess.py:93} INFO - A Requisição de nº 4 coletou 50 Pokemons
[2023-10-20T14:57:37.625+0000] {subprocess.py:93} INFO - A Requisição de nº 5 coletou 50 Pokemons
[2023-10-20T14:57:37.625+0000] {subprocess.py:93} INFO - A Requisição de nº 6 coletou 50 Pokemons
[2023-10-20T14:57:37.625+0000] {subprocess.py:93} INFO - A Requisição de nº 7 coletou 50 Pokemons
[2023-10-20T14:57:37.625+0000] {subprocess.py:93} INFO - A Requisição de nº 8 coletou 50 Pokemons
[2023-10-20T14:57:37.626+0000] {subprocess.py:93} INFO - A Requisição de nº 9 coletou 50 Pokemons
[2023-10-20T14:57:37.627+0000] {subprocess.py:93} INFO - A Requisição de nº 10 coletou 50 Pokemons
[2023-10-20T14:57:37.627+0000] {subprocess.py:93} INFO - A Requisição de nº 11 coletou 50 Pokemons
[2023-10-20T14:57:37.627+0000] {subprocess.py:93} INFO - A Requisição de nº 12 coletou 50 Pokemons
[2023-10-20T14:57:37.627+0000] {subprocess.py:93} INFO - A Requisição de nº 13 coletou 50 Pokemons
[2023-10-20T14:57:37.631+0000] {subprocess.py:93} INFO - A Requisição de nº 14 coletou 50 Pokemons
[2023-10-20T14:57:37.631+0000] {subprocess.py:93} INFO - A Requisição de nº 15 coletou 50 Pokemons
[2023-10-20T14:57:37.631+0000] {subprocess.py:93} INFO - A Requisição de nº 16 coletou 50 Pokemons
[2023-10-20T14:57:37.632+0000] {subprocess.py:93} INFO - A Requisição de nº 17 coletou 50 Pokemons
[2023-10-20T14:57:37.632+0000] {subprocess.py:93} INFO - A Requisição de nº 18 coletou 50 Pokemons
[2023-10-20T14:57:37.632+0000] {subprocess.py:93} INFO - A Requisição de nº 19 coletou 50 Pokemons
[2023-10-20T14:57:37.632+0000] {subprocess.py:93} INFO - A Requisição de nº 20 coletou 50 Pokemons
[2023-10-20T14:57:37.633+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:37.637+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
[2023-10-20T14:57:37.640+0000] {subprocess.py:93} INFO -     httplib_response = self._make_request(
[2023-10-20T14:57:37.640+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
[2023-10-20T14:57:37.642+0000] {subprocess.py:93} INFO -     self._validate_conn(conn)
[2023-10-20T14:57:37.642+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
[2023-10-20T14:57:37.642+0000] {subprocess.py:93} INFO -     conn.connect()
[2023-10-20T14:57:37.642+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
[2023-10-20T14:57:37.643+0000] {subprocess.py:93} INFO -     self.sock = ssl_wrap_socket(
[2023-10-20T14:57:37.643+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
[2023-10-20T14:57:37.783+0000] {subprocess.py:93} INFO -     ssl_sock = _ssl_wrap_socket_impl(
[2023-10-20T14:57:37.787+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
[2023-10-20T14:57:37.788+0000] {subprocess.py:93} INFO -     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
[2023-10-20T14:57:37.788+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/ssl.py", line 501, in wrap_socket
[2023-10-20T14:57:37.801+0000] {subprocess.py:93} INFO -     return self.sslsocket_class._create(
[2023-10-20T14:57:37.812+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/ssl.py", line 1074, in _create
[2023-10-20T14:57:37.813+0000] {subprocess.py:93} INFO -     self.do_handshake()
[2023-10-20T14:57:37.820+0000] {subprocess.py:93} INFO -   File "/usr/local/lib/python3.9/ssl.py", line 1343, in do_handshake
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO -     self._sslobj.do_handshake()
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO - ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1129)
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:37.831+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:37.832+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
[2023-10-20T14:57:37.897+0000] {subprocess.py:93} INFO -     resp = conn.urlopen(
[2023-10-20T14:57:37.903+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
[2023-10-20T14:57:37.904+0000] {subprocess.py:93} INFO -     retries = retries.increment(
[2023-10-20T14:57:37.912+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
[2023-10-20T14:57:37.915+0000] {subprocess.py:93} INFO -     raise MaxRetryError(_pool, url, error or ResponseError(cause))
[2023-10-20T14:57:37.915+0000] {subprocess.py:93} INFO - urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pokeapi.co', port=443): Max retries exceeded with url: /api/v2/pokemon/?offset=1000&limit=50 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2023-10-20T14:57:37.915+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:37.933+0000] {subprocess.py:93} INFO - During handling of the above exception, another exception occurred:
[2023-10-20T14:57:37.985+0000] {subprocess.py:93} INFO - 
[2023-10-20T14:57:37.986+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-10-20T14:57:37.986+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/pokelist.py", line 29, in <module>
[2023-10-20T14:57:38.000+0000] {subprocess.py:93} INFO -     response = requests.get(url)
[2023-10-20T14:57:38.022+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/api.py", line 73, in get
[2023-10-20T14:57:38.022+0000] {subprocess.py:93} INFO -     return request("get", url, params=params, **kwargs)
[2023-10-20T14:57:38.022+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/api.py", line 59, in request
[2023-10-20T14:57:38.022+0000] {subprocess.py:93} INFO -     return session.request(method=method, url=url, **kwargs)
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -     resp = self.send(prep, **send_kwargs)
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -     r = adapter.send(request, **kwargs)
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.9/site-packages/requests/adapters.py", line 517, in send
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO -     raise SSLError(e, request=request)
[2023-10-20T14:57:38.023+0000] {subprocess.py:93} INFO - requests.exceptions.SSLError: HTTPSConnectionPool(host='pokeapi.co', port=443): Max retries exceeded with url: /api/v2/pokemon/?offset=1000&limit=50 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[2023-10-20T14:57:41.492+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-10-20T14:57:41.620+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-10-20T14:57:41.749+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=simple, task_id=pokelist, execution_date=20231020T144635, start_date=20231020T145417, end_date=20231020T145741
[2023-10-20T14:57:41.977+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 87 for task pokelist (Bash command failed. The command returned a non-zero exit code 1.; 6185)
[2023-10-20T14:57:42.118+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-20T14:57:42.188+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
